### ISSUE TITLE
GraphQL schema design? ✨

### ISSUE THREAD

**Issue by xavxyz** [partyparrot/codetours#11]
I'm wondering how the Codetours GraphQL schema will look like.

I thought at first about two major nodes, `Tour` & `Step`, linked by a `stepSlug` edge, but while looking at the data stored in Mongo, I see that there is **a common pattern between a step and its sections**:

```graphql
# step schema
type Step {
  ...githubRelatedFields
  ...tourRelatedFields
  slug: String
  lineStart: Float
  lineEnd: Float
  content: [ repetition of these 4 fields ] # [ sections ]
}
```

So should this "4-common-field" set become a type in itself?

Before simplifying the component codes, it must be smarter to rethink the schema first, isn't it?

Sketch highlighting this repetition
![drawing](https://cl.ly/0R2I421K0u0I/IMG_20170313_170204.jpg)

**Comment by stubailo** [comment]
I think actually we should just have a step have sections, and remove those fields from Step. So every step has at least one section.

**Comment by xavxyz** [comment]
Nom nom nom, work in progress that's a lot of fun!

![graphiql screenshot](https://d3uepj124s5rcx.cloudfront.net/items/2J3y0T3U3Q1i0C2J0d24/Image%202017-03-16%20at%2011.58.11%20PM.png?v=31a1a72e)

It's still basic at the moment, and I hit some errors cause actually some steps don't have sections haha 😄

I'll go forward on that and open a PR. Do you think we could have a quick chat about *how to go GraphQL First on CodeTours* in the upcoming days?

**Comment by stubailo** [comment]
Sure! You want to do a call about it? Maybe email me and we can talk tomorrow? sashko@meteor.com
