### ISSUE TITLE
Empty database or something is broken?

### ISSUE THREAD

**Issue by xavxyz** [partyparrot/codetours#7]
Hey @stubailo @zhangela! 👋  

I find CodeTours being a super initiative and I'm about forking the starter kit to document how we use Apollo in Telescope ([apollo branch](https://github.com/TelescopeJS/Telescope/tree/apollo)).

When reaching [codetours.xyz](https://www.codetours.xyz/), no tours available on the front page 😞  I've noticed that the publication `tours` doesn't send any data and is never ready & that the codetour starter url is on loading (publications `tours` & `steps` never ready).

Is there something broken (#4) or have you empty the database?

Cheers!

**Comment by stubailo** [comment]
Interesting, thanks for reporting - just logged into the db hosting dashboard and it all looks fine. I also didn't deploy any new code. Going to check the logs.

**Comment by stubailo** [comment]
<img width="951" alt="screenshot 2016-11-08 12 07 48" src="https://cloud.githubusercontent.com/assets/448783/20115135/fdcb0b38-a5ab-11e6-8c7d-c2cd36088adc.png">

Odd, I wonder if the db connection URL changed or something.

**Comment by stubailo** [comment]
Gonna try to restart the container.

**Comment by stubailo** [comment]
Looks like it works now, thanks for the report!

**Comment by xavxyz** [comment]
Awesome! Well, thanks for all the cool things you build 😉
