### ISSUE TITLE
Provide easy method to progress through intra-page sections

### ISSUE THREAD

**Issue by lorensr** [partyparrot/codetours#8]
Equivalent to clicking the next "Click to highlight" left section. Eg by clicking a prominent arrow or hit the down/right arrow or space key.

And then when you do the action on the last left section, it moves to the next page / top-level section.

**Comment by stubailo** [comment]
That's a really good call since right now it's not even obvious you can click on those!

**Comment by xavxyz** [comment]
Fixed by #16 👍
